"""Generate random sentences with exact token counts.

Supports token counts: 3, 5, 7, 9, 11, 13, 15, 19, 23. Uses template
based generation with rejection sampling to match the exact count for
a given tokenizer.
"""

import random

import transformers

NOUNS = [
    # Animals
    "cat",
    "dog",
    "bird",
    "fish",
    "horse",
    "bear",
    "wolf",
    "deer",
    "fox",
    "rat",
    "cow",
    "pig",
    "duck",
    "frog",
    "lion",
    "snake",
    "whale",
    "mouse",
    "goat",
    "bee",
    "ant",
    "bat",
    "hawk",
    "crow",
    "dove",
    "owl",
    "moth",
    "crab",
    "worm",
    "ox",
    "hen",
    "ram",
    "yak",
    # People
    "man",
    "girl",
    "boy",
    "king",
    "queen",
    "child",
    "guard",
    "cook",
    "nurse",
    "judge",
    "chief",
    "monk",
    "knight",
    "saint",
    "lord",
    "priest",
    "thief",
    "clerk",
    "coach",
    "pilot",
    "agent",
    "bride",
    "twin",
    "fool",
    "guest",
    "host",
    "witch",
    "prince",
    # Objects
    "door",
    "book",
    "chair",
    "stone",
    "light",
    "bell",
    "car",
    "ship",
    "clock",
    "lamp",
    "rope",
    "coin",
    "flag",
    "drum",
    "sword",
    "blade",
    "shield",
    "crown",
    "mask",
    "ring",
    "key",
    "box",
    "cup",
    "bowl",
    "plate",
    "fork",
    "knife",
    "pen",
    "map",
    "bag",
    "hat",
    "boot",
    "coat",
    "shirt",
    "glove",
    "chain",
    "wheel",
    "boat",
    "cart",
    "net",
    "pipe",
    "lock",
    "nail",
    "wire",
    "brick",
    "tile",
    "lens",
    "ball",
    "rod",
    "pin",
    "bed",
    "desk",
    "shelf",
    "bench",
    "stool",
    "rug",
    "broom",
    "torch",
    "candle",
    "scroll",
    "spear",
    "axe",
    "bow",
    "horn",
    # Nature
    "tree",
    "hill",
    "cloud",
    "road",
    "wall",
    "river",
    "rain",
    "wind",
    "star",
    "fire",
    "lake",
    "moon",
    "sun",
    "storm",
    "wave",
    "rock",
    "sand",
    "dirt",
    "ice",
    "snow",
    "flame",
    "pond",
    "cliff",
    "cave",
    "marsh",
    "field",
    "wood",
    "vine",
    "root",
    "leaf",
    "seed",
    "bloom",
    "ridge",
    "peak",
    "shore",
    "reef",
    "dust",
    "mud",
    "fog",
    "creek",
    "hedge",
    "thorn",
    "moss",
    "oak",
    "pine",
    "ash",
    "rose",
    "sage",
    "mint",
    "bay",
    # Places/structures
    "house",
    "barn",
    "bridge",
    "church",
    "fort",
    "mill",
    "well",
    "tower",
    "camp",
    "port",
    "hall",
    "gate",
    "fence",
    "path",
    "trail",
    "den",
    "tomb",
    "vault",
    "lodge",
    "hut",
    # Food/drink
    "bread",
    "cheese",
    "wine",
    "milk",
    "meat",
    "salt",
    "fruit",
    "cake",
    "soup",
    "rice",
    "grain",
    "herb",
    "spice",
    "jam",
    "pie",
    "stew",
    "cream",
    "juice",
    "beer",
    "tea",
    "grape",
    "plum",
    # Body
    "hand",
    "eye",
    "face",
    "head",
    "arm",
    "leg",
    "bone",
    "heart",
    "blood",
    "skin",
    "tooth",
    "hair",
    "throat",
    "chest",
    "lip",
    "palm",
    "fist",
    "heel",
    "spine",
    # Time/events
    "dawn",
    "dusk",
    "night",
    "day",
    "week",
    "year",
    "hour",
    "birth",
    "death",
    "war",
    "peace",
    "crime",
    "trial",
    "fight",
    "hunt",
    "flood",
    "drought",
    "plague",
    "siege",
    # Materials
    "gold",
    "iron",
    "steel",
    "silk",
    "wool",
    "cloth",
    "glass",
    "clay",
    "coal",
    "tin",
    "bronze",
    "chalk",
    "wax",
    "oil",
    "ink",
    "dye",
    "gem",
    "pearl",
    # Abstract
    "song",
    "voice",
    "sound",
    "noise",
    "dream",
    "thought",
    "sign",
    "mark",
    "code",
    "rule",
    "plan",
    "spell",
    "curse",
    "trick",
    "feast",
    "dance",
    "game",
    "race",
    "test",
    "gift",
    "prize",
    "trade",
    "deal",
    "bond",
    "debt",
    "loss",
    "gain",
    "risk",
    "fault",
    "truth",
]

ADJECTIVES = [
    "old",
    "big",
    "small",
    "red",
    "blue",
    "dark",
    "cold",
    "warm",
    "bright",
    "tall",
    "new",
    "soft",
    "hard",
    "loud",
    "green",
    "white",
    "young",
    "deep",
    "wide",
    "thin",
]

VERBS_PAST = [
    "ran",
    "walked",
    "jumped",
    "fell",
    "sat",
    "stood",
    "moved",
    "turned",
    "called",
    "pulled",
    "sang",
    "found",
    "left",
    "held",
    "watched",
    "played",
    "opened",
    "closed",
    "built",
    "lost",
    "slept",
    "woke",
    "spoke",
    "wrote",
    "read",
    "cried",
    "laughed",
    "smiled",
    "waved",
    "fought",
    "fled",
    "hid",
    "climbed",
    "crawled",
    "danced",
    "flew",
    "froze",
    "grew",
    "hung",
    "kept",
    "leapt",
    "lied",
    "lived",
    "looked",
    "paid",
    "prayed",
    "reached",
    "rode",
    "rose",
    "rushed",
    "sailed",
    "searched",
    "served",
    "shook",
    "sighed",
    "slid",
    "slipped",
    "split",
    "spread",
    "stayed",
    "stole",
    "stopped",
    "struck",
    "swore",
    "taught",
    "threw",
    "trusted",
    "voted",
    "waited",
    "wandered",
    "wished",
    "worked",
    "yelled",
    "yielded",
    "aimed",
    "asked",
    "bowed",
    "burned",
    "caught",
    "changed",
    "charged",
    "cheered",
    "chose",
    "claimed",
    "cooked",
    "crossed",
    "dared",
    "drank",
    "drew",
    "dried",
    "dropped",
    "earned",
    "escaped",
    "failed",
    "feared",
    "fired",
    "fixed",
    "flowed",
    "followed",
    "gained",
    "gasped",
    "gathered",
    "gave",
    "glanced",
    "grabbed",
    "grinned",
    "guessed",
    "healed",
    "heard",
    "helped",
    "hoped",
    "hunted",
    "hurt",
    "joined",
    "joked",
    "judged",
    "kicked",
    "kissed",
    "knocked",
    "landed",
    "lasted",
    "launched",
    "leaned",
    "learned",
    "lifted",
    "listened",
    "locked",
    "marched",
    "missed",
    "named",
    "needed",
    "nodded",
    "noted",
    "packed",
    "passed",
    "paused",
    "picked",
    "planned",
    "planted",
    "pointed",
    "poured",
    "pressed",
    "promised",
    "proved",
    "pushed",
    "quit",
    "raised",
    "rested",
    "returned",
    "roared",
    "rolled",
    "ruled",
    "saved",
    "screamed",
    "sealed",
    "sank",
    "shared",
    "shipped",
    "shouted",
    "showed",
    "shrunk",
    "shut",
    "signed",
    "solved",
    "sparked",
    "spun",
    "stared",
    "started",
    "stumbled",
    "suffered",
    "survived",
    "swept",
    "swung",
    "thanked",
    "thought",
    "tossed",
    "trained",
    "trapped",
    "traveled",
    "tried",
    "twisted",
    "used",
    "vanished",
    "warned",
    "welcomed",
    "whispered",
    "won",
    "wondered",
    "worried",
    "wrapped",
    "ate",
    "bent",
    "bit",
    "blew",
    "broke",
    "brought",
    "bought",
    "bore",
    "bound",
    "cast",
    "chased",
    "cleared",
    "crept",
    "crushed",
    "cursed",
    "cut",
    "dealt",
    "dug",
    "dragged",
    "drifted",
    "drove",
    "dove",
    "faced",
    "faded",
    "fed",
    "felt",
    "filled",
    "fit",
    "flipped",
    "floated",
    "forced",
    "formed",
    "frowned",
    "gazed",
    "got",
    "gripped",
    "guarded",
    "guided",
    "halted",
    "handed",
    "hauled",
    "headed",
    "hugged",
    "jammed",
    "led",
    "lent",
    "let",
    "lit",
    "loaded",
    "loved",
    "made",
    "meant",
    "met",
    "mixed",
    "owned",
    "paced",
    "parked",
    "patched",
    "peeled",
    "pinned",
    "placed",
    "pleaded",
    "plunged",
    "praised",
    "raged",
    "raced",
    "rang",
    "replied",
    "saw",
    "seized",
    "sent",
    "shot",
    "skipped",
    "slammed",
    "snapped",
    "soared",
    "sold",
    "sought",
    "spilled",
    "sprang",
    "squeezed",
    "stamped",
    "stepped",
    "stirred",
    "stretched",
    "struggled",
    "studied",
    "tapped",
    "tasted",
    "tore",
    "touched",
    "traced",
    "traded",
    "urged",
    "washed",
    "bred",
]

ADVERBS = [
    "quickly",
    "slowly",
    "gently",
    "loudly",
    "quietly",
    "calmly",
    "softly",
    "briefly",
    "proudly",
    "boldly",
    "gladly",
    "sadly",
    "firmly",
    "eagerly",
    "neatly",
    "fairly",
]

PREPS = [
    "in the park",
    "on the hill",
    "by the lake",
    "near the door",
    "past the bridge",
    "through the gate",
    "down the road",
    "up the stairs",
    "at the farm",
    "from the shop",
    "over the wall",
    "under the tree",
    "along the path",
    "toward the light",
    "around the bend",
]

TIME_PHRASES = [
    "at dawn",
    "at noon",
    "last night",
    "each day",
    "that morning",
    "all summer",
    "one evening",
    "by sunset",
    "after lunch",
    "before dark",
]

DETERMINERS = [
    "The",
    "A",
    "My",
    "His",
    "Her",
    "Our",
    "One",
    "Each",
    "That",
    "This",
    "No",
]
SUBJECTS = ["She", "He", "It", "They", "We", "I"]

# Templates per target token count. Rejection sampling with tokenizer handles exact count.
TEMPLATES: dict[int, list[str]] = {
    3: [
        "{det} {noun}.",
        "{subj} {verb_past}.",
    ],
    5: [
        "The {adj} {noun} {verb_past}.",
        "A {noun} {verb_past} {adverb}.",
        "The {noun} {verb_past} {time}.",
    ],
    7: [
        "The {adj} {noun} {verb_past} {prep}.",
        "A {noun} {adverb} {verb_past} {time}.",
        "The {adj} {noun} {verb_past} {adverb} {time}.",
    ],
    9: [
        "The {adj} {noun} {adverb} {verb_past} {prep}.",
        "A {adj} {noun} {verb_past} {prep} {time}.",
        "The {noun} and the {noun2} {verb_past} {prep}.",
    ],
    11: [
        "The {adj} {noun} {adverb} {verb_past} {prep} {time}.",
        "A {adj} {noun} and a {adj2} {noun2} {verb_past} {prep}.",
        "The {adj} {noun} {verb_past} {prep} while the {noun2} {verb_past2}.",
    ],
    13: [
        "The {adj} {noun} {verb_past} {prep} while the {noun2} {adverb} {verb_past2}.",
        "The {adj} {noun} and the {adj2} {noun2} {verb_past} {adverb} {prep}.",
    ],
    15: [
        "The {adj} {noun} and the {adj2} {noun2} {verb_past} {adverb} {prep} {time}.",
        "A {adj} {noun} and a {adj2} {noun2} {adverb} {verb_past} {prep} {time}.",
    ],
    19: [
        "The {adj} {noun} {adverb} {verb_past} {prep} while the {adj2} {noun2} {verb_past2} {prep2} {time}.",
        "A {adj} {noun} and a {adj2} {noun2} {adverb} {verb_past} {prep} and then {verb_past2} {prep2} {time}.",
        "The {adj} {noun} {verb_past} {prep} {time} and the {adj2} {noun2} {adverb} {verb_past2} {prep2}.",
    ],
    23: [
        "The {adj} {noun} {adverb} {verb_past} {prep} {time} while the {adj2} {noun2} {adverb2} {verb_past2} {prep2} and then {verb_past3}.",
        "A {adj} {noun} and a {adj2} {noun2} {verb_past} {adverb} {prep} {time} and the {noun3} {adverb2} {verb_past2} {prep2}.",
        "The {adj} {noun} {verb_past} {prep} and the {adj2} {noun2} {adverb} {verb_past2} {prep2} while the {noun3} {verb_past3} {time}.",
    ],
}

VALID_LENGTHS = sorted(TEMPLATES.keys())
MAX_ATTEMPTS = 200


def _fill_template(template: str, rng: random.Random) -> str:
    """Fill a sentence template with random words."""
    return template.format(
        det=rng.choice(DETERMINERS),
        subj=rng.choice(SUBJECTS),
        noun=rng.choice(NOUNS),
        noun2=rng.choice(NOUNS),
        noun3=rng.choice(NOUNS),
        adj=rng.choice(ADJECTIVES),
        adj2=rng.choice(ADJECTIVES),
        verb_past=rng.choice(VERBS_PAST),
        verb_past2=rng.choice(VERBS_PAST),
        verb_past3=rng.choice(VERBS_PAST),
        adverb=rng.choice(ADVERBS),
        adverb2=rng.choice(ADVERBS),
        prep=rng.choice(PREPS),
        prep2=rng.choice(PREPS),
        time=rng.choice(TIME_PHRASES),
    )


def sample_sentence(
    n_tokens: int,
    tokenizer: transformers.AutoTokenizer,
    rng: random.Random | None = None,
) -> str:
    """Return a random sentence with exactly ``n_tokens`` tokens.

    Args:
        n_tokens: Target token count. Must be one of {3, 5, 7, 9, 11, 13, 15, 19, 23}.
        tokenizer: Any tokenizer with an ``encode(str) -> list[int]`` method.
        rng: Optional ``random.Random`` instance for reproducibility.

    Returns:
        A sentence string that tokenizes to exactly ``n_tokens`` tokens.

    Raises:
        ValueError: If ``n_tokens`` is not a supported length.
        RuntimeError: If no matching sentence is found after ``MAX_ATTEMPTS`` attempts.
    """
    if n_tokens not in TEMPLATES:
        raise ValueError(f"n_tokens must be one of {VALID_LENGTHS}, got {n_tokens}")
    r = rng or random.Random()
    templates = TEMPLATES[n_tokens]

    for _ in range(MAX_ATTEMPTS):
        template = r.choice(templates)
        sentence = _fill_template(template, r)
        if len(tokenizer.encode(sentence, add_special_tokens=False)) == n_tokens:  # type: ignore[attr-defined]
            return sentence

    raise RuntimeError(
        f"Could not generate a sentence with exactly {n_tokens} tokens after {MAX_ATTEMPTS} attempts"
    )
